name: onayamijika
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.20.0
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  flutter_riverpod: ^1.0.4
  cloud_firestore: ^3.4.3
  salomon_bottom_bar: ^3.3.1
  flip_card: ^0.6.0
  card_swiper: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true